ry/block-rotation
thecardkid/SoftSysBombassticBamboo pull request #14
Opened 2017-04-03 17:15 UTC by RachelYang02

integrated keypress and rotation so that "f" rotates block clockwise and "d" rotates block counter-clockwise.
had to add parameter to move_block in controller.c for rotation parameter so that grid would clear properly.

2017-04-03 17:56 UTC, thecardkid requested changes

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +  /* Rotates block 90 degrees CLOCKWISE.
move docstrings to header file

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +  /* Rotates block 90 degrees COUNTER-CLOCKWISE.
^

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +    int matC[4][2]={0};
can you change matC to something more descriptive. Also afaik `= {0}` is not necessary here

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +          sum=sum+(b->cells[i][k])*rotation_matrix[k][j];
+= instead. Also can you add spaces in assignments?

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +    int i,j,k,z,r=4,c=2;
`z` is unused here, and i don't think you need to declare any of these ints. you can do `for (int i...)` and compile with make

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +    for(i=0;i<r;i++){     //row of first matrix
Can you add spaces in for loops --> `for_(...)_{...}`

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +    int i,j,k,z,r=4,c=2;
On second thought, declare `sum` here instead

2017-04-03 17:56 UTC, thecardkid commented on src/rotate.c
> +  switch(b->type) {
switch not necessary here. i think:
`if (O) return; else rotate`
is clearer. but not a big deal

2017-04-03 17:56 UTC, thecardkid commented on Makefile
> +	  $(BUILD_DIR)/scorer.o $(BUILD_DIR)/rotate.o \
remove the trailing `\`

2017-04-03 17:56 UTC, thecardkid commented on src/controller.c
> +            move_block(s, -1, 0);
can you declare this as an enum in `utils.h` so that {-1,0,1} becomes {LEFT, NO_ROTATE, RIGHT} or something like that

2017-04-03 17:56 UTC, thecardkid commented on src/controller.c
> +        switch(rotation){
spaces (see below regarding for loops)

2017-04-04 16:43 UTC, RachelYang02 commented on src/rotate.c
> +    int i,j,k,z,r=4,c=2;
need to keep declaration of sum=0 within for loop

2017-04-04 19:08 UTC, thecardkid requested changes

2017-04-04 19:08 UTC, thecardkid commented on src/utils.h
> +typedef enum {LEFT=-1, NO_ROTATE=0, RIGHT=1} rotation;
capitalize for consistency with other enums

2017-04-04 19:08 UTC, thecardkid commented on src/controller.h
> +int move_block(State* state, int delta_x, int rotation);
Since this is an enum, change to accept `Rotation r` instead of `int rotation`

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +    }}};
Separate lines for closing braces

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +  if (b->type == O) {return;}
Looks like indented with 2 spaces? Change to 4

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +  if (b->type == O) {return;}
4 spaces plz

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +    for (int i=0;i<4;i++) {     //row of first matrix
Can you add spaces after semicolons. for consistency. here and the two for loops below as well

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +      int sum=0;
Sum should be declared outside for loops and set to 0 inside. Also add spaces to assignments

```
int sum;

for {
...
   sum = 0;
}
```

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +          rotated_cells[i][j]=sum;
spaces here plz `a = b`

2017-04-04 19:08 UTC, thecardkid commented on src/rotate.c
> +  if (b->type == O) {return;}
Also: can you put `return` on a separate line. and you don't need the else clause here

2017-04-04 19:08 UTC, thecardkid commented on src/controller.c
> +            if (!move_block(s, 0, 0)) {
Change to use your new enum

2017-04-04 19:30 UTC, thecardkid requested changes

2017-04-04 19:30 UTC, thecardkid commented on src/utils.h
> +typedef enum {LEFT=-1, NO_ROTATE=0, RIGHT=1} Rotation;
No need for ints here. when you `typedef enum` it implicitly cast as ints.

2017-04-04 19:30 UTC, thecardkid commented on src/rotate.c
> +    for (int i = 0; i < 4; i++) {     //row of first matrix
The indentation of these 3 for loops don't look right

2017-04-04 19:30 UTC, thecardkid commented on src/rotate.c
> +        for (int k = 0; k < 2; k++) {
this looks like 2 spaces

2017-04-04 19:30 UTC, thecardkid commented on src/controller.h
> +int move_block(State* state, int delta_x, int rotation);
Change to `Rotation r`

2017-04-04 19:30 UTC, thecardkid commented on src/controller.c
> +          case 0: break;
Indentation looks wrong for the `case`s

2017-04-04 19:55 UTC, thecardkid approved these changes

2017-04-04 19:55 UTC, merged