Db/movements v2
thecardkid/SoftSysBombassticBamboo pull request #19
Opened 2017-04-04 21:52 UTC by Daniel6

- Reworked the way movements and collisions work to be more robust
- Added framework for pausing and stuff
- Added endgame case

2017-04-04 22:15 UTC, thecardkid submitted a review, later dismissed

2017-04-04 22:15 UTC, thecardkid commented on src/utils.h
> +typedef enum {RUNNING, PAUSED, SHUTDOWN, BOSS} Gamemode;
can you change this and the `Rotation` enum above to not be all caps, since those should be reserved for constants

2017-04-04 22:15 UTC, thecardkid commented on src/controller.c
> +            if (m->r == NO_ROTATE) m->r = RIGHT;
"Braces plz" - Shane Kelly

2017-04-04 22:15 UTC, thecardkid commented on src/controller.c
> +            if (m->r == LEFT) m->r = NO_ROTATE;
"So" - Shane Kelly

2017-04-04 22:15 UTC, thecardkid commented on src/controller.c
> +            if (m->r == NO_ROTATE) m->r = LEFT;
"few" - Shane Kelly

2017-04-04 22:15 UTC, thecardkid commented on src/controller.c
> +            if (m->r == RIGHT) m->r = NO_ROTATE;
"braces" - Shane Kelly

2017-04-04 22:27 UTC, Daniel6 commented on src/utils.h
> +typedef enum {RUNNING, PAUSED, SHUTDOWN, BOSS} Gamemode;
Shouldn't we treat the different types of rotations and modes as constants though?

2017-04-04 22:29 UTC, Daniel6 commented on src/utils.h
> +typedef enum {RUNNING, PAUSED, SHUTDOWN, BOSS} Gamemode;
[http://stackoverflow.com/a/3069863](http://stackoverflow.com/a/3069863)

2017-04-04 22:49 UTC, thecardkid commented on src/utils.h
> +typedef enum {RUNNING, PAUSED, SHUTDOWN, BOSS} Gamemode;
huh. then i guess at some point i'll push a pr for the BlockColor ones then

2017-04-04 23:30 UTC, Daniel6 commented
added braces as per shane's review

2017-04-05 03:46 UTC, PrimePalaver requested changes

2017-04-05 03:46 UTC, shanek21 commented on src/controller.c
> +            if (m->r == NO_ROTATE) {m->r = RIGHT;}
Could you move these one-liner if statements onto multiple lines?

if (m->r == NO_ROTATE) {
    m->r = RIGHT;
}

2017-04-05 03:57 UTC, Daniel6 commented on src/controller.c
> +            if (m->r == NO_ROTATE) {m->r = RIGHT;}
dun

2017-04-05 04:44 UTC, PrimePalaver approved these changes

2017-04-05 04:54 UTC, thecardkid approved these changes

2017-04-05 05:08 UTC, merged